name: Nanjundeshwara_Stores
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  upi_pay: ^1.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  url_launcher: ^6.1.5
  razorpay_flutter: ^1.3.0
  uni_links: ^0.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/father.jpg
    - assets/jerry.gif
    - assets/mother.jpg
    - assets/owner.jpg
    - assets/shop.jpg
    - assets/things/atta.jpg
    - assets/things/chilly.jpg
    - assets/things/coriander.jpg
    - assets/things/jaggery.jpg
    - assets/things/kumkumjpg.jpg
    - assets/things/maida.jpg
    - assets/things/matchjpg.jpg
    - assets/things/oil.jpg
    - assets/things/pattasu.jpg
    - assets/things/payasam.jpg
    - assets/things/ricejpg.jpg
    - assets/things/riceraw.jpg
    - assets/things/salt.jpg
    - assets/things/semiya.jpg
    - assets/things/sesame.jpg
    - assets/things/sugar.jpg
    - assets/things/tamrind.jpg
    - assets/things/tumeric.jpg
    - assets/things/whitedall.jpg
    - assets/things/camphor.jpg
    - assets/things/image.jpg


  uses-material-design: true